name: sdu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Навигация
  auto_route: ^10.1.0+1

  # Для SVG-изображений (нужен, раз включаем flutter_svg интеграцию)
  flutter_svg: ^2.0.10+1

  # State Management
  flutter_bloc: ^8.1.6

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # Dependency Injection
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Генераторы
  flutter_gen_runner: ^5.5.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/icons/
    - .env

flutter_gen:
  # Куда положить assets.gen.dart
  output: lib/core/assets
  line_length: 80
  integrations:
    flutter_svg: true
